modality: "abdominal_ct"

# Define findings categories and their associated questions
categories:
  Pancreas:
    description: "Pancreas-related findings"
    questions:
      - question: "Is there pancreatic atrophy?"
      - question: "Is chronic pancreatitis suspected based on imaging findings?"
      - question: "Is there acute pancreatitis?"
      - question: "Is there necrotizing pancreatitis?"
      - question: "Is there autoimmune pancreatitis?"
      - question: "Is there groove pancreatitis?"
      - question: "Is there any pancreatic pseudocysts?"
      - question: "Are there any pancreatic tumors?"
      - question: "Are there any intraductal papillary mucinous neoplasms (IPMN)?"
      - question: "Are there any intraductal papillary mucinous neoplasms with worrisome features?"
      - question: "Are there any serous cystic neoplasms?"
      - question: "Are there any mucinous cystic neoplasms?"
      - question: "Are there any solid pseudopapillary tumors?"
      - question: "Are there any ductal pancreatic carcinomas?"
      - question: "Are there any neuroendocrine tumors?"
      - question: "Is there main pancreatic duct dilatation?"
      - question: "Is there an annular pancreas?"
      - question: "Is cystic fibrosis suspected based on the pancreatic imaging findings?"
      

  Spleen:
    description: "Spleen-related findings"
    questions:
      - question: "Is there splenomegaly?"
      - question: "Are there any epithelial cysts?"
      - question: "Are there any splenic pseudocysts?"
      - question: "Are there any splenic hamartomas?"
      - question: "Is splenic lymphoma present?"
      - question: "Are there any splenic abscesses?"
      - question: "Are there any splenic lacerations?"
      - question: "Are there any splenic infarcts?"
      - question: "Is the spleen surgically absent? Are there any post-splenectomy changes?"
      - question: "Are there any accessory spleens?"

  Biliary Tree:
    description: "Biliary tree-related findings"
    questions:
      - question: "Is there any intrahepatic biliary ductal dilation?"
      - question: "is there any extrahepatic biliary ductal dilation?"
      - question: "Are there any intra-hepatic stones?"
      - question: "Is there ascending cholangitis?"
      - question: "Is there primary sclerosing cholangitis?"
      - question: "Is there periductal/intraductal cholangiocarcinoma?"
      - question: "Are there any biliary cystadenomas?"
      - question: "Are there any biliary hamartomas?"

  Liver:
    description: "Liver-related findings"
    questions:
      - question: "Is there hepatomegaly?"
      - question: "Is hepatic steatosis, fatty liver, focal fatty infiltration suspected based on the imaging findings?"
      - question: "Is there cirrhosis?"
      - question: "Is there cirrhosis with portal hypertension?"
      - question: "Is there cirrhosis with decompensation?"
      - question: "Are there any esophageal or gastric varices?"
      - question: "Are there any hepatic regenerative nodules?"
      - question: "Are there any dysplastic nodules?"
      - question: "Is polycystic liver disease present?"
      - question: "Is there viral hepatitis?"
      - question: "Are there any hepatic abscesses?"
      - question: "Is there hemochromatosis?"
      - question: "Are there any hepatic cysts?"
      - question: "Are there any hepatic hemangiomas?"
      - question: "Are there any hepatic focal nodular hyperplasias?"
      - question: "Are there any hepatic adenomas?"
      - question: "Are there any hepatic masses?"
      - question: "Is there hepatocellular carcinoma?"
      - question: "Is there hepatoblastoma?"
      - question: "Is there cholangiocarcinoma?"
      - question: "Are there any hepatic metastases?"
      - question: "Is there hepatic lymphoma?"
      - question: "Is there angiosarcoma?"
      - question: "Is there epithelioid hemangioendothelioma?"
      - question: "Is there fibrolamellar carcinoma?"
      - question: "Are there any liver lacerations?"
      - question: "Are there any sites of active extravasation in the liver?"
      - question: "Are there any hepatic infarcts?"
      - question: "Are there any hepatic changes post-resection?"
      - question: "Are there any hepatic changes post-transplantation?"
      - question: "Is there portal venous occlusion?"
      - question: "Is there any portal venous gas?"
      
      
  Gallbladder:
    description: "Gallbladder-related findings"
    questions:
      - question: "Are there any gallbladder stones or cholelithiasis?"
      - question: "Is the gallbladder surgically absent?"
      - question: "Are there any choledochal cysts?"
      - question: "Is there acute cholecystitis?"
      - question: "Is there acute cholecystitis with rupture?"
      - question: "Is there emphysematous cholecystitis?"
      - question: "Is there porcelain gallbladder?"
      - question: "Is there pneumobilia?"
      - question: "Is there gallbladder wall thickening?"
      - question: "Is there gallbladder adenomyomatosis?"
      - question: "Are there any gallbladder polyps?"
      - question: "Is there gallbladder cancer?"

  Genitourinary:
    description: "Kidney and urinary tract findings"
    questions:
      - question: "Is there hydronephrosis?"
      - question: "Are there any renal hypodensities?"
      - question: "Are there any simple renal cysts?"
      - question: "Are there any complex renal cysts?"
      - question: "Is there nephritis?"
      - question: "Are there any renal abscesses?"
      - question: "Is there xanthogranulomatous pyelonephritis?"
      - question: "Are there any renal stones / nephrolithiasis?"
      - question: "Are there any ureteral stones?"
      - question: "Are there any bladder stones?"
      - question: "Is there nephrocalcinosis?"
      - question: "Is there polycystic kidney disease?"
      - question: "Is there horseshoe kidney?"
      - question: "Are there any ureteroceles?"
      - question: "Are there any urachal diverticula?"
      - question: "Are there any renal cell carcinomas?"
      - question: "Are there any oncocytomas?"
      - question: "Is there renal lymphomas?"
      - question: "Are there any Wilms tumors?"
      - question: "Are there any angiomyolipomas?"
      - question: "Are there any bladder transitional cell carcinomas?"
      - question: "Are there any post-nephrectomy changes?"
      - question: "Are there any post-renal transplantation changes?"
      - question: "Are there any subcapsular hemorrhages?"
      - question: "Are there any renal lacerations?"
      - question: "Are there any renal infarcts?"
      - question: "Is there bladder rupture?"

  Adrenal gland:
    description: "Adrenal gland findings"
    questions:
      - question: "Are there any adrenal masses?"
      - question: "Are there any adrenal adenomas?"
      - question: "Are there any pheochromocytomas?"
      - question: "Are there any adrenal myelolipomas?"
      - question: "Is there adrenal hyperplasia?"
      - question: "Are there any adrenal hemorrhages?"
      - question: "Are there any adrenal infarcts?"

  Gastrointestinal:
    description: "Gastrointestinal findings"
    questions:
      - question: "Is appendicitis suspected based on the imaging findings?"
      - question: "Is there submucosal edema, enterocolitis, or gastritis?"
      - question: "Is bowel obstruction present?"
      - question: "Is hiatal hernia present?"
      - question: "Is there pneumatosis intestinalis?"
      - question: "Is there inflammatory bowel disease?"
      - question: "Is there pseudomembranous colitis?"
      - question: "Is there diverticulitis?"
      - question: "Is there bowel obstruction?"
      - question: "Is there small bowel obstruction?"
      - question: "Is there ileus?"
      - question: "Is there volvulus?"
      - question: "Is there large bowel obstruction?"
      - question: "Is there hiatal hernia?"
      - question: "Is there intussusception?"
      - question: "Are there any enteric duplication cysts?"
      - question: "Is there achalasia or scleroderma suspected based on gastrointestinal imaging findings?"
      - question: "Are there any enteric diverticula?"
      - question: "Is there gastric volvulus?"
      - question: "Are there any inguinal hernias?"
      - question: "Are there any femoral/ventral/Spigelian hernias?"
      - question: "Is there evidence of sleeve gastrectomy or fundoplication?"
      - question: "Is there a surgical gastric conduit?"
      - question: "Are there any gastric foreign bodies (not related to medical devices or post-surgical changes)?"
      - question: "Is there any evidence of enteric contrast leak suggestive of postoperative leakage/fistula after surgery?"
      - question: "Are there any gastric carcinomas?"
      - question: "Are there any esophageal carcinomas?"
      - question: "Are there any duodenal carcinomas?"
      - question: "Are there any colonic carcinomas?"
      - question: "Are there any rectal carcinomas?"
      - question: "Are there any gastrointestinal stromal tumors (GISTs)?"
      - question: "Is there gastrointestinal lymphoma?"

  Device:
    description: "Medical devices/hardware/implants"
    questions:
      - question: "Are there any nasogastric tubes?"
      - question: "Are there any gastrostomy tubes?"
      - question: "Are there any drainage catheters?"
      - question: "Are there any biliary stents?"
      - question: "Are there any transjugular intrahepatic portosystemic shunts?"
      - question: "Are there any Foley catheters?"
      - question: "Are there any percutaneous nephrostomy tubes/catheters?"
      - question: "Are there any ureteral double-J catheters/stents?"
      - question: "Are there any intra-uterine devices?"
      - question: "Are there any extracorporeal membrane oxygenation (ECMO) devices?"
      - question: "Are there any central venous catheters?"
      - question: "Are there any aortic stents?"

  Peritoneum:
    description: "Peritoneal cavity findings"
    questions:
      - question: "Is there any ascites?"
      - question: "Is there any free air or pneumoperitoneum?"
      - question: "Is there pseudomyxoma peritonei?"
      - question: "Is there peritoneal carcinomatosis or omental caking?"
      - question: "Is there mesenteric carcinoid tumor?"

  Great Vessel:
    description: "Vascular findings in the abdomen"
    questions:
      - question: "Is abdominal aortic aneurysm suspected based on the imaging findings?"
      - question: "Is arterial or aortic thrombosis suspected based on the imaging findings?"
      - question: "Is aortic atherosclerosis suspected based on the imaging findings?"
      - question: "Are there any aortic stents?"
      - question: "Are there any deep venous thromboses?"
      - question: "Are there any aortic dissections?"
      - question: "Are there any aortic intramural hematomas?"
      - question: "Are there any penetrating atherosclerotic aortic ulcers?"

  Retroperitoneum:
    description: "Retroperitoneal space findings"
    questions:
      - question: "Is there any lymphadenopathy in retroperitoneum, peritoneum or pelvis?"
      - question: "Is there retroperitoneal fibrosis?"
      - question: "Is there retroperitoneal hemorrhage or retroperitoneal hematomas?"
      - question: "Is there retroperitoneal liposarcoma?"
      

  Multi Organs:
    description: "Findings affecting multiple organ systems"
    questions:
      - question: "Is metastatic disease suspected based on the imaging findings?"
      - question: "Is anasarca suspected based on the imaging findings?"

  Male Pelvis:
    description: "Male pelvic findings"
    questions:
      - question: "Is there prostatomegaly or prostatic hyperplasia?"
      - question: "Is there prostatitis?"
      - question: "Is there prostate cancer?"
      - question: "Is there testicular torsion?"
      - question: "Are there any testicular masses?"
      - question: "Is there testicular (segmental) infarct?"
      - question: "Are there any scrotal hematomas?"
      - question: "Is there epididymitis?"
      - question: "Are there any hydroceles?"
      - question: "Are there any varicoceles?"

  Female pelvis:
    description: "Female pelvic findings"
    questions:
      - question: "Are there any leiomyomas?"
      - question: "Are there any leiomyosarcomas?"
      - question: "Is there any adenomyosis?"
      - question: "Is there endometrial thickening?"
      - question: "Are there any endometrial polyps?"
      - question: "Are there any uterine malformations?"
      - question: "Are there changes status post hysterectomy?"
      - question: "Are there any cervical masses?"
      - question: "Are there any Nabothian cysts?"
      - question: "Is there adenoma malignum?"
      - question: "Are there any ovarian tumors?"
      - question: "Are there any endometriomas?"
      - question: "Are there any ovarian cancers?"
      - question: "Is there adnexal torsion?"
      - question: "Are there any ovarian teratomas?"
      - question: "Is there polycystic ovarian syndrome?"
      - question: "Is there deep infiltrative endometriosis?"
      - question: "Is there pelvic inflammatory disease?"
      - question: "Are there any Bartholin gland cysts?"
      - question: "Are there any Gartner duct cysts?"
      - question: "Are there any vaginal or vulvar cancers?"
  

  Musculoskeletal:
    description: "Musculoskeletal findings"
    questions:
      - question: "Is osteopenia suspected based on the imaging findings?"
      - question: "Are there any fractures (general)?"
      - question: "Are there any spinal fractures?"
      - question: "Are there any fractures of the pelvic girdle or sacrum?"
      - question: "Are there any femoral fractures?"
      - question: "Are there any rib fractures?"
      - question: "Are there any osteolytic lesions?"
      - question: "Are there any osteosclerotic lesions?"
      - question: "Are there any iliopsoas muscle abscesses?"
      - question: "Is there Fournier's gangrene / necrotizing fasciitis?"
      

  Visible Thoracic:
    description: "Findings visible in the lower thorax"
    questions:
      - question: "Is there any atelectasis in the visible lung?"
      - question: "Is there any pleural effusion?"
      - question: "Is there cardiomegaly?"
      - question: "Are there any aortic valve calcifications?"
      - question: "Are there coronary artery calcifications?"
      - question: "Is there any consolidation?"
      - question: "Are there any lung masses or nodules?"
      - question: "Is there any coronary atherosclerosis?"
